run:
  target:
    entity:
      integration: moen_smart_faucet
      domain: valve
  fields:
    temperature:
      selector:
        number:
          min: 5
          max: 60
          step: 1
          unit_of_measurement: "°C"
    preset:
      selector:
        select:
          translation_key: preset
          options:
            - hottest
            - coldest
    flow_rate:
      selector:
        number:
          min: 30
          max: 100
          step: 1
          unit_of_measurement: "%"
dispense:
  target:
    entity:
      integration: moen_smart_faucet
      domain: valve
  fields:
    volume:
      required: true
      example: 500
      selector:
        number:
          min: 0
          max: 4000
          step: any
          mode: box
    unit:
      default: mL
      selector:
        select:
          translation_key: unit
          options:
            - mL
            - L
            - tbsp
            - fl_oz
            - cup
            - pint
            - quart
            - gal
    temperature:
      selector:
        number:
          min: 5
          max: 60
          step: 1
          unit_of_measurement: "°C"
    preset:
      selector:
        select:
          translation_key: preset
          options:
            - hottest
            - coldest
    start:
      default: now
      selector:
        select:
          translation_key: start
          options:
            - now
            - on_wave
